name: Gerar APK Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Baixar arquivos do repositório
        uses: actions/checkout@v4

      - name: Compilar APK com Docker Kivy
        run: |
          docker run --rm \
            --volume ${{ github.workspace }}:/home/user/hostcwd \
            kivy/buildozer:latest \
            android debug

      - name: Salvar APK para download
        uses: actions/upload-artifact@v4
        with:
          name: InspecaoAterro-APK
          path: bin/*.apk
          retention-days: 30
